Repository AxonIQ/axoniq-library-site, pull requests merged in 2024-10, with the labels that each got.

#40 Replace trailing `.html` for `/` and add "latest" symlink
  playbook.yaml
Labels: Priority 1: Must, Type: Feature

#41 Added listing page for Axon Framework extensions
  content/axon-framework-extensions/antora.yml
  content/axon-framework-extensions/modules/ROOT/pages/index.adoc
Labels: Priority 1: Must, Type: Enhancement

#43 42/textual enhancement
  content/axon-server-faq/modules/ROOT/pages/as-faq.adoc
  content/axon-server-installation-guides/modules/ROOT/pages/installing_as_docker-k8s.adoc
  content/contribution-guide/modules/ROOT/pages/design/doc-system.adoc
  content/contribution-guide/modules/ROOT/pages/overview/build.adoc
  content/home/modules/ROOT/pages/index.adoc
  content/home/modules/guides/pages/axon-framework.adoc
  content/home/modules/guides/pages/axon-server.adoc
  content/home/modules/guides/pages/index.adoc
  content/legacy_docs_af/modules/ROOT/pages/index.adoc
  content/legacy_docs_as/modules/ROOT/pages/index.adoc
Labels: Priority 1: Must, Type: Enhancement

#45 Add dependabot configuration
  .github/dependabot.yml
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#49 Add Kroki with mermaid support
  .github/workflows/check_pr.yml
  .github/workflows/publish.yml
  docker-compose.yml
  playbook-dev.yaml
  playbook.yaml
Labels: Priority 1: Must, Type: Enhancement

#50 Update 404 page
  playbook.yaml
Labels: Priority 2: Should, Type: Enhancement

#52 Removal of Contribution Guide package
  README.adoc
  content/contribution-guide/antora.yml
  content/contribution-guide/modules/ROOT/images/doc-system.png
  content/contribution-guide/modules/ROOT/images/needs_improvement.png
  content/contribution-guide/modules/ROOT/nav.adoc
  content/contribution-guide/modules/ROOT/pages/design/doc-system.adoc
  content/contribution-guide/modules/ROOT/pages/index.adoc
  content/contribution-guide/modules/ROOT/pages/overview/build.adoc
  content/contribution-guide/modules/ROOT/pages/overview/content-sources.adoc
  content/contribution-guide/modules/ROOT/pages/overview/platform.adoc
  content/contribution-guide/modules/ROOT/pages/writing/mark4improvement.adoc
  content/contribution-guide/modules/ROOT/pages/writing/menu.adoc
  content/contribution-guide/modules/ROOT/pages/writing/tabs.adoc
  content/home/modules/ROOT/nav.adoc
Labels: Priority 2: Should, Type: Enhancement
